#!/usr/bin/env php
<?php

use DI\Container;
use Gutenberg\Adapter\Database\BookAdapter;
use Gutenberg\Middleware\MySQLSave;
use Gutenberg\Parser\CoverParser;
use Gutenberg\Parser\GutenbergRDFParser;
use Gutenberg\Parser\TermsParser;
use Gutenberg\Parser\TestCloudkit;

include "./bootstrap.php";

/** @global Container $container */

$start = new DateTime();
$options = getopt("p:f:", ["process:"]);
$process = strtolower($options["p"] ?? "none");
$folder = strtolower($options["f"] ?? "none");

echo "processing $process" . PHP_EOL;
if ($process === "all") {
    $container->call(TermsParser::class);
}

if ($process === "terms") {
    $container->call(TermsParser::class);
}

if ($process === "rdf") {
    $ignored = [56057]; // These files are not parsable at the moment
    $folders = explode(PHP_EOL, shell_exec('ls -1 "$(pwd)/cache/epub"'));
    $imagick = new Imagick("./tmp/custom_cover.jpg");
    foreach ($folders as $folder) {
        if (!is_numeric($folder) || in_array((int)$folder, $ignored)) {
            continue;
        }
        $book = $container->call(GutenbergRDFParser::class, ["folder" => (int) $folder]);
        $container->call(CoverParser::class, ["img" => $imagick, "book" => $book]);
        $container->call(MySQLSave::class, ["gutenbergBook" => $book]);
        gc_collect_cycles();
    }
}

if ($process === "import") {
    $ignored = ["56057", "test"];
    if (in_array($folder, $ignored)) {
        echo "Did not process {$folder}" . PHP_EOL;
        exit;
    }
    echo "Importing {$folder}" . PHP_EOL;
    $book = $container->call(GutenbergRDFParser::class, ["folder" => (int) $folder]);
    $container->call(CoverParser::class, ["img" => new Imagick("./tmp/custom_cover.jpg"), "book" => $book]);
    $container->call(MySQLSave::class, ["gutenbergBook" => $book]);
}

if ($process === "download") {
    echo shell_exec('rm -rf "$(pwd)/cache/cache/"');
    echo shell_exec('curl -o "$(pwd)/cache/rdf-files.tar.bz2" https://www.gutenberg.org/cache/epub/feeds/rdf-files.tar.bz2');
    echo shell_exec('tar -xf "$(pwd)/cache/rdf-files.tar.bz2" -C "$(pwd)"');
}

$end = new DateTime();
$diff = $start->diff($end);
echo PHP_EOL . "Process time: " . $diff->format( '%H:%I:%S');