#!/usr/bin/env php
<?php

use DI\Container;
use Gutenberg\Parser\TermsParser;
use Gutenberg\Parser\TestCloudkit;

include "./bootstrap.php";

/** @global Container $container */


$options = getopt("p:", ["process:"]);

$process = strtolower($options["p"] ?? "none");

echo "processing $process" . PHP_EOL;
if ($process === "all") {
    $container->call(TermsParser::class);
}

if ($process === "terms") {
    $container->call(TermsParser::class);
}

if ($process === "test") {
    $book = $container->call(\Gutenberg\Parser\GutenbergRDFParser::class, ["folder" => 1]);
    echo json_encode($book, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
}

if ($process === "download") {
    echo shell_exec('rm -rf "$(pwd)/cache/cache/"');
    echo shell_exec('curl -o "$(pwd)/cache/rdf-files.tar.bz2" https://www.gutenberg.org/cache/epub/feeds/rdf-files.tar.bz2');
    echo shell_exec('tar -xf "$(pwd)/cache/rdf-files.tar.bz2" -C "$(pwd)"');
}